### ISSUE TITLE
Publish actual code to NPM

### ISSUE THREAD

**Issue by pauln** [Hiswe/vh-check#10]
Although (at least some) earlier versions published to NPM include the actual library, the latest (v1.1.2) doesn't appear to contain the library itself (no `dist` or `src` folders).  Can you please publish a new version which includes the code, so that `npm i vh-check` will result in a usable version being installed?

**Comment by Hiswe** [comment]
@pauln right away 😶

**Comment by Hiswe** [comment]
@pauln I've just tested it with a new install with this `package.json` & `app.js`

I've found nothing wrong.
In the `node_modules` folder I have:

<img width="161" alt="image" src="https://user-images.githubusercontent.com/96121/38911190-c1ea3d10-42f7-11e8-9eb4-c0375529fe9b.png">


#### package.json

```json
{
  "name": "vh-test",
  "scripts": {
    "build": "webpack app.js --mode development"
  },
  "dependencies": {
    "vh-check": "^1.1.2"
  },
  "devDependencies": {
    "webpack": "^4.6.0",
    "webpack-cli": "^2.0.14"
  }
}
```

#### app.js

```js
const vhCheck = require( 'vh-check' )

console.log( vhCheck() )
```

**Comment by pauln** [comment]
Hmm, something strange is going on here.  Initially, npm wasn't giving me the `dist` folder for version `^1.1.2` - but it appeared when I changed my dependency to `1.1.1` and re-ran `npm i`.  However, now it seems to be giving me the `dist` folder for `^1.1.2` as expected, even after clearing `npm`'s cache...

Thanks for investigating, and sorry for wasting your time!

**Comment by Hiswe** [comment]
No problems.

I haven't tested with the cached cleared though.
