### ISSUE TITLE
Doesn't apply to Chrome / Android

### ISSUE THREAD

**Issue by matthew-dean** [Hiswe/vh-check#12]
AFAIK, Chrome on mobile browsers also has this behavior. See: https://developers.google.com/web/updates/2016/12/url-bar-resizing

So this shouldn't be an "iOS" gap, but should apply to all mobile browsers that have "vh" mean "viewport height as if the address bar was hidden".

**Comment by Hiswe** [comment]
Thanks for the info. 
I've read that chrome would align the vh computing to Safari iOS but didn't follow when they would do it. 
The code should work in both cases as it doesn't rely on browser sniffing. 
I will update the readme and the package.json to make it more neutral.

**Comment by Hiswe** [comment]
@matthew-dean I've updated the doc and tested in Chrome Android, it's working as expected.

Is there anything more?
