### ISSUE TITLE
Not working on new chrome ios

### ISSUE THREAD

**Issue by nikse** [Hiswe/vh-check#16]
Hey, just found this a few days and think it's great and solves a very annoying problem. However it seems to not be working on the newly updated google chrome V69.0.3497.105 for ios

**Comment by Hiswe** [comment]
Hi,

Thank you for using this lib and thanks for reporting this issue.
I can effectively reproduce this behavior on chrome V69.0.3497.105 for ios & firefox ios…
It's ok with Safari, Chrome & Firefox for android…

I'll try to fix that tomorrow

**Comment by nikse** [comment]
Awesome, I can confirm the same behavior. Thanks for the quick response and turnaround!

**Comment by Hiswe** [comment]
@nikse In fact it's working.

In those browsers the `vh` unit reevaluate on scroll: 
  - so the initial 100vh are matching the visible content
  - so the lib doesn't see any size difference
  - so it returns a `no-needed`

I've 
  - detailed [the readme](https://github.com/Hiswe/vh-check#%EF%B8%8F-chrome-ios--firefox-ios) about this. 
  - updated [the demo](https://hiswe.github.io/vh-check/) to see better what's going on.

Is this ok for you?

**Comment by nikse** [comment]
Ah, interesting yeah that explains it. Though, I will say this is still undesirable behavior from the browser. I'm wondering if an event or anything is fired once the address bar is removed/added and the vh could be set to the max of either of those or if you can think of any other alternative for the current ios chrome/firefox behavior

**Comment by Hiswe** [comment]
I don't know about such events.
I think it's more a bug than a real feature. They should align with all the other behavior.

Still if you want to override that you should be able to to do something like that:

```js
vhCheck({
  bind: false,
  redefineVh: true,
})
```

```css
.my-div {
  height: calc(var(--vh, 1vh) * 100)
}
```

`--vh` will be defined once at load time and will not reevaluate on scroll

**Comment by nikse** [comment]
thanks!
