### ISSUE TITLE
IE11 - Object doesn't support property or method 'assign'

### ISSUE THREAD

**Issue by john-griffin** [Hiswe/vh-check#18]
Just tried to upgrade from `1.1.3` to `2.0.1` but get the following error in IE 11.

<img width="328" alt="screen shot 2018-10-02 at 12 58 25" src="https://user-images.githubusercontent.com/19490/46364309-7736f900-c643-11e8-94e0-ade45e07be06.png">

**Comment by Hiswe** [comment]
Hi,
Thank for the catch.
I'll fix it tomorrow.

**Comment by Hiswe** [comment]
@john-griffin done in `2.0.2`

Thanks again 😄

**Comment by john-griffin** [comment]
@Hiswe thanks for quick fix!
