### ISSUE TITLE
Issues with TypeScript

### ISSUE THREAD

**Issue by apptaro** [Hiswe/vh-check#20]
**Issue 1:**
In TypeScript,
`import vhCheck from "vh-check";`

Will result in the error:
`Could not find a declaration file for module 'vh-check'.`

Adding the following in package.json will resolve the issue:
`  "typings": "dist/vh-check.d.ts",`

**Issue 2:**
Compiling the app with vh-check will result in the error:
```
ERROR in xxx/node_modules/vh-check/dist/vh-check-types.d.ts
A rest parameter must be of an array type.
> 1 | export declare type Callback = (...arg: any) => void;
```
Modifying the first line of vh-check-types.d.ts as below fixes the issue:
`export declare type Callback = (arg: any[]) => void;`

**Versions:**
vh-check@2.0.4
typescript@3.0.3

**Comment by Hiswe** [comment]
@apptaro Thanks for the insights, I'll fix it promptly

I'm still a typescript newbee :bee:

**Comment by Hiswe** [comment]
@apptaro can you check the updated master if everything in order?

**Comment by apptaro** [comment]
Looks good to me. I see types in package.json has been already added four days ago. I will wait for the new release.

**Comment by Hiswe** [comment]
ok published.
Let me know if everything's fine

**Comment by apptaro** [comment]
@Hiswe I have updated the library, and everything is fine. Thank you!
