### ISSUE TITLE
Help: How can I use it with sass or vue?

### ISSUE THREAD

**Issue by pmochine** [Hiswe/vh-check#21]
I feel like I'm dumb.. I even asked it on [StackOverflow](https://stackoverflow.com/questions/53836822/sass-does-not-render-css-variables) but had no luck. 

How would you use this when you are using sass/scss or vue?

Let us say I have this:

```
<style>
	:root {
	  --vh-offset: 0px;
	  --vh: 1vh;
	}
	.f-body #app{
		min-height: calc(100vh - var(--vh-offset));
	}
</style>
```

it always compiles to `min-height: calc(100vh - 0px));` 

Because of this, the offset from javascript cannot work.

Thank you for reading/helping!

**Comment by pmochine** [comment]
Okay! I found out what the problem was.

In my webpack file I had precss as postcss required. However, this contains a predefined var function and compiles it to that. 

So removing precss in webpack fixed the issue

**Comment by Hiswe** [comment]
@pmochine glad you can find it!

I should add this in the readme :)
