### ISSUE TITLE
root object in factory is undefined

### ISSUE THREAD

**Issue by janwidmer** [Hiswe/vh-check#6]
Hi There,

Thanks for the great script. I Tried to use it in normal js environment without CommonJS / RequireJS.  If I do so, I get an exception at line 7 (  root.vhCheck = factory(); )

"Factory is undefined"

Any idea, what I am doing wrong?

**Comment by Hiswe** [comment]
Hi,

Thanks for using this lib!

If you run the demo as specified [here](https://github.com/Hiswe/vh-check#demo) and open the `test-global.html` do you still have the same error ?

By the way, it's strange that `Factory` has an uppercase `F`

**Comment by janwidmer** [comment]
Running npm test gives me the error

```
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/jawidmer/.nvm/versions/node/v6.9.4/bin/node" "/Users/jawidmer/.nvm/versions/node/v6.9.4/bin/npm" "test"
npm ERR! node v6.9.4
npm ERR! npm  v4.2.0
npm ERR! path /Users/jawidmer/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/Users/jawidmer/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/Users/jawidmer/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jawidmer/.npm/_logs/2017-02-06T14_09_58_700Z-debug.log
```

**Comment by Hiswe** [comment]
@janwidmer you should run the commands inside the `vh-check` folder, at the same level as the *package.json*

**Comment by janwidmer** [comment]
ah yeah, sorry..my bad. Your demo works.. so I guess, my environment somehow leads to that behaviour.. in your demo, the root parameter is the window as it should be, in my case, it is always undefined..

**Comment by Hiswe** [comment]
Are you compressing the file in anyway ? or using it along other files ? In which browser are you using it ?

**Comment by janwidmer** [comment]
It gets assembled to an app.js file, which contains all js files.. I am using it in chrome vs. 55

**Comment by Hiswe** [comment]
So it may be while concatenating  your files that the window object becomes unaccessible to my script.
You should try to load it independently to see if it comes from here or not.

**Comment by janwidmer** [comment]
ok I'll try that..since it works in your demo, its clearly related to my build..I will therefore close the issue. Thanks for your help
