### ISSUE TITLE
gap doesn't reevaluate on scroll

### ISSUE THREAD

**Issue by Hiswe** [Hiswe/vh-check#7]
On iPad tabs auto-hide when scrolling.
And so the gap will reduce ¬_¬'

**Comment by Hiswe** [comment]
Up to the developer to implement it.
Listening to scroll can be costly…

**Comment by ChrisButterworth** [comment]
Couldn't this be attached to `gesturechange` that should be more performant?
I feel this is still an issue that can be fixed

**Comment by Hiswe** [comment]
@ChrisButterworth It seems that [GestureEvent](https://developer.mozilla.org/en-US/docs/Web/API/GestureEvent) is non-standard.

It should be easy to attach yourself an event handler to recompute the custom property. You have a good [example here](https://css-tricks.com/the-trick-to-viewport-units-on-mobile/#article-header-id-2)
But right now it's kind of broken because any call to vh-check will result in adding another listener to the `orientationchange` event 😞 

I'm still working on an update to handle that

**Comment by ChrisButterworth** [comment]
I've edited the distributable file to combat this and used `touchmove` instead of `gesturechange` so it works better; will submit a pull request later with the src edited to give the output.

**Comment by ChrisButterworth** [comment]
Submitted pull request #15
