### ISSUE TITLE
usefullness check

### ISSUE THREAD

**Issue by vhs-kid** [Hiswe/vh-check#8]
Hello, 

Very useful script, but does line 40 should exist? 
I guess it says to return nothing when offset is 0, but CSS expects some value and fails when there isn't any.
I got it working by deleting 'usefullness check'...

**Comment by Hiswe** [comment]
Hi @vhs-kid,

in fact if you follow “progressive enhancement” philosophy, you should have a pure CSS fallback.
So the JS code follow this thing: if it isn't needed, it just lets CSS to handle the regular behaviour.

I should add it to the doc :)
